### PR TITLE
Delete README.md

### PR DESCRIPTION
**Pull request by Riccadonny**
TU1CmpmWbCrFXqLLqMaKL2Q1d34bJNYLJe

## **Please provide the following information for your Defi project.**
Please include change to the `defiProjectList.json` file in the PR.
DON'T modify any other project's contents.

### CODE REVIEW

**Comment by Riccadonny** [comment]
I love my business

**Comment by Ngochan95** [comment]
Ngochan

**Review by Dayooor — APPROVED** [review]

**Comment by Dayooor** [comment]
Can I send out Bitcoin on here

**Review by inderashah007 — APPROVED** [review]

**Comment by Blonde488** [comment]
hope you like this!!

**Comment by Blonde488** [comment]
hope you like this!!

**Review by Judykoniel — COMMENTED** [review]
****

**Pull request closed without merging**
